- name: "Install Bitwarden CLI application"
  ansible.builtin.include_tasks: install/main.yml

- name: "Create Bitwarden CLI utility script"
  ansible.builtin.include_tasks: create_util_script/main.yml

- name: "Log in and unlock Bitwarden Vault, as required"
  ansible.builtin.include_tasks: login_to_vault/main.yml

