# the role will create a Bitwarden CLI utility script with this name
bitwarden_cli_utility_script_file_name: 'do_bitwarden_cli.sh'

# email address (i.e. login / user-name) of main Bitwarden CLI user
bitwarden_cli_user_email_addr: ''

