- name: "Check FreeBSD Linux Compat running, required for linux-bitwarden-cli install"
  ansible.builtin.command:
    cmd: "{{ bitwarden_check_freebsd_linux_compat_cmd }}"
  changed_when: false

- name: "Install the 'linux-bitwarden-cli' application package"
  ansible.builtin.package:
    name: linux-bitwarden-cli
    state: present
  become: true
  become_user: root

